version: '3.8'

services:
  backend:
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:80"

  python-app:
    image: ${DOCKER_REGISTRY-}python-app
    build:
      context: ./llm_worker
      dockerfile: Dockerfile
    ports:
      - "80:80"

  nginx:
    image: nginx:alpine
    volumes:
      - ./static-html-directory:/usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on:
      - backend

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: hackathon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
